### ISSUE TITLE
lib not published

### ISSUE THREAD

**Issue by hyphaene** [jaketrent/redux-types#8]
Hi, there is another problem : 
the Npm publish has not being done while the package was built, so lib isn't avaible and for now the package is broken.

Just need to build it again and then publish it on npm ;)

**Comment by jaketrent** [comment]
I removed semantic release because it wasn't detecting new changes because latest git logs haven't followed the commit log convention.  

I did the npm publish manually.  There is a build step prepublish, but for some reason the `lib` directory wasn't being copied.  Not sure why, but adding `directories.lib` to package.json fixes this.

@hyphaene Thanks for the heads up.  Please download v2.0.2 and let me know how it goes.

**Comment by hyphaene** [comment]
So if I am correct, there was a convention for the commits that I didn't follow ? ( would you a ressource to point to me so I won't make the same mistake the next time ?

About the 2.0.2, it does fix the build, thanks.

**Comment by jaketrent** [comment]
Hey @hyphaene .  It's no prob at all btw.  I never really liked the commit convention solution here.  The convention was fine, just not the tooling around it, imo.

Anyway, the project used to use https://commitizen.github.io/cz-cli/

These days I like using this tooling: https://jaketrent.com/post/enforce-git-commit-message-format/

I'm glad the build's working.  Cheers!
